### ISSUE TITLE
Plugin not loading any wallpapers

### ISSUE THREAD

**Issue by r1c4rd0** [sal0max/muzei-thevergewallpapers#1]
Tried to load the plugin last week but there were no wallpapers and it won't download any wallpapers anymore. The national geographic one seems to work fine tho.

**Comment by sal0max** [comment]
Please provide more information:

- Phone
- Android Version
- Muzei Version
- App Version

**Comment by r1c4rd0** [comment]
Yes, it's a Samsung S20Ultra 
Android 13
Muzei 3.4.5
Ver 1.0.4

**Comment by somu1795** [comment]
Same for me as well.

Phone: Samsung S23 Ultra
Android Version: 14 (One UI 6.0 - latest)
Muzei Version: v3.5.0-rc01

**Comment by sal0max** [comment]
It's weird, as I can't reproduce it. Working really fine on my devices and the Emulators.

One thing: The wallpapers are quite large and take several seconds to download, even on a 100Mbit+ plan.
How much time have you given the plugin? What internet speed do you have?

**Comment by KjmT6459** [comment]
Phone: Google Pixel 8 (Unlocked)
Android Version: 14 (fully updated)
Muzei Version: 3.5.0-rc01 (F-droid)
App Version: 1.0.4 (F-droid)

Looking at network connections, it looks to me like the app isn't sending out any requests. Time waited doesn't make a difference.

**Comment by sal0max** [comment]
Thanks for the information. I could reproduce the error and found a solution.
ab089af25f0a44fa8e351aab7850a5d1fb4b92e5

Update coming soon.

**Comment by r1c4rd0** [comment]
I just tried the new update. It's working great. Thanks!
